branch-defaults:
  default:
    environment: aya-udagrams
    group_suffix: null
deploy:
  artifact: www/Archive.zip
environment-defaults:
  aya-udagrams:
    branch: null
    repository: null
global:
  application_name: aya-udagrams
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
  deploy:
  artifact: www/Archive.zip
